version: "3.9"

services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    networks:
      - internal
    volumes:
      - ./config/nginx_default.conf:/etc/nginx/conf.d/default.conf

  backend:
    image: tmauricioic/ci-test:latest
    ports:
      - 5000
    networks:
      - internal

networks:
  internal:
