# This is a basic workflow to help you get started with Actions

name: Tests

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  PYTHON_VERSION: "3.9"

jobs:
  prep:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install pip --upgrade
          python -m pip install -r requirements.txt

      - name: Run Pylint
        run: |
          find ./app -type f -name "*.py" | xargs pylint

      #- name: Test with pytest
      #  run: pytest

  # how to push to docker hub
  publish:
    runs-on: ubuntu-latest
    needs: prep

    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Login in docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: "Build and push image"
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ci-test:latest,${{ secrets.DOCKERHUB_USERNAME }}/ci-test:${{ env.RELEASE_VERSION }}

  # how to push to google container registry
  # publish:
  #   runs-on: ubuntu-latest
  #   needs: prep
  #   env:
  #     IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT_ID }}/ci-test

  #   steps:
  #     - name: Login
  #       uses: google-github-actions/setup-gcloud@v0
  #       with:
  #         project_id: ${{ secrets.GCP_PROJECT_ID }}
  #         service_account_email: ${{ secrets.GCP_EMAIL }}
  #         service_account_key: ${{ secrets.GCP_ACC_KEY }}

  #     - name: Configure Docker
  #       run: gcloud auth configure-docker --quiet

  #     - name: Checkout repository
  #       uses: actions/checkout@v2

  #     - name: Set env
  #       run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

  #     - name: Build Docker image
  #       run: docker build . -t $IMAGE_NAME:${{ env.RELEASE_VERSION }}

  #     - name: Push Docker image
  #       run: docker push $IMAGE_NAME:${{ env.RELEASE_VERSION }}

  #     - name: Deploy Docker image
  #       run: gcloud run deploy ${{ secrets.GCP_PROJECT_ID }} --image $IMAGE_NAME:${{ env.RELEASE_VERSION }} --region us-central1 --platform managed --port=5000

  # deploy to a GCP VM
